jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm ci
        working-directory: backend-expressjs

      - name: Create .env file
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > backend-expressjs/.env

      - name: Start backend
        run: |
          cd backend-expressjs
          nohup npm start > server.log 2>&1 &
          sleep 5

      - name: Install ngrok
        run: npm install -g ngrok

      - name: Start ngrok tunnel
        id: ngrok
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 3000 > ngrok.log &
          sleep 5
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok URL: $NGROK_URL"
          echo "::set-output name=ngrok_url::$NGROK_URL"

      - name: Output ngrok URL
        run: echo "Public URL from ngrok: ${{ steps.ngrok.outputs.ngrok_url }}"
